### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by kraftpunk97** [PaulPauls/SuperMarioWorld-NEAT-Agent#1]
Hi. I am interested in studying NEAT, specially its applications in RL. The Super Mario World use-case looks very interesting. Your project is one of the more recent ones that I could find. Do you mind sharing the progress you were able to make? Thanks 😀

**Comment by PaulPauls** [comment]
Hi kraftpunk, I am glad you like the project! I have not pursued any progress on this project further as it was more of a demonstration of what's possible with the current NEAT libraries.

I have in the meantime however created the [Tensorflow-Neuroevolution](https://github.com/PaulPauls/Tensorflow-Neuroevolution) framework and am working on it continuously (and will do so for the coming months). If you are interested in NEAT check out the branch ['create_neat_algorithm'](https://github.com/PaulPauls/Tensorflow-Neuroevolution/tree/create_neat_algorithm). I expect to finish this development branch in this or the coming week and will merge it with the master, adding NEAT, OpenAI Gym environments and hopefully the SuperMarioWorld environment to the framework and entering beta stage for the framework. I also intend to write a short blog post about this framework in the next month, so I can hopefully introduce this framework to a wider audience.

I also think my [review paper](https://github.com/PaulPauls/Neuroevolution_of_Augmenting_Topologies_Paper) on NE/NEAT, detailing the current state of neuroevolution with focus on NEAT, could be of interest to you. 

Best,
Paul
